#!/bin/bash
# Based on http://git.overlays.gentoo.org/gitweb/?p=proj/localepurge.git;a=summary
# да-да "ненужно" :3
# Deleting all locale files on ${D} *not* listed in ${LINGUAS}

[[ "${EBUILD_PHASE}" != "install" ]] && return 0

live-localepurge(){
set -e
VERSION="0.2"

for lang in ${LINGUAS};do
	if [[ ${lang} != *_* ]];then
		up=$(tr '[:lower:]' '[:upper:]' <<< "${lang}")
		LINGUAS+=" ${lang}_${up}"
	else
		p="$(cut -d '_' -f1 <<< "${lang}")"
		LINGUAS+=" ${p}"
	fi
done

normal=$'\e[0m'
bold=$'\e[1m'

remove() {
	local action="rm -vf"
	local dir_action="rm -vfr"
	local removepath="${1}"
	${action} $(find ${removepath} -type f -o -type l 2>/dev/null)
	[ -z "$(find ${removepath} -type f -o -type l 2>/dev/null)" ] && ${dir_action} ${removepath}
}

purgelocale(){
	local all_dirs good_locales trash_list all_qm good_qm trash_qm
	all_dirs="$(find ${D} -type d -name 'LC_MESSAGES')"
	if [ -n "${all_dirs}" ];then
		for lang in ${LINGUAS};do
			good_locales+="/${lang}/LC_MESSAGES"$'\n'
		done
		trash_list="$(grep -v "${good_locales%$'\n'}" <<< "${all_dirs}")" || return 0
		for DIR in ${trash_list};do
			remove "${DIR%/LC_MESSAGES}"
		done
	fi
	all_qm="$(find ${D} -type f -name "*.qm" 2>/dev/null)"
	if [ -n "${all_qm}" ];then
		for lang in ${LINGUAS};do
			good_qm+="${lang}.qm"$'\n'
		done
		trash_qm="$(grep -v "${good_qm%$'\n'}" <<< "${all_qm}")" || return 0
		for qm in ${trash_qm};do
			remove "${qm}"
		done
	fi
}

purgeman(){
	local man_dirs good_man subdirs trash_list
	man_dirs="$(find ${D} -type d -name 'man')"
	if [ -n "${man_dirs}" ];then
		for DIR in ${man_dirs};do
			subdirs="$(ls -d1 ${DIR}/* | grep -v "/man[1-9]")" || return 0
		done
		for lang in ${LINGUAS};do
			good_man+="/man/${lang}"$'\n'
		done
		trash_list="$(grep -v "${good_man%$'\n'}" <<< "${subdirs}")" || return 0
		for DIR in ${trash_list};do
			remove "${DIR}"
		done
	fi
}

space_before="$(du -s "${D}" | cut -f1)"
space_before="${space_before:-0}"

purgelocale;
purgeman;

space_after="$(du -s "${D}" | cut -f1)"
space_after="${space_after:-0}"

total="$(($space_before - $space_after))"
total="${total:-0}"

if (( ${total} > 0 ));then
	elog "Total disk space freed by live-localepurge: ${bold}"${total}"K${normal}"
fi
}

if [[ "$(declare -F post_src_install)" ]];then
	eval "$(declare -f post_src_install | sed "s|^}|live-localepurge;}|")"
else
	post_src_install(){ live-localepurge;}
fi
